//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderingInvoicingApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PredicaOrders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PredicaOrders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderingInvoicingApp.Resources.PredicaOrders", typeof(PredicaOrders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string PredicaColContracInvoiceDescr {
            get {
                return ResourceManager.GetString("PredicaColContracInvoiceDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string PredicaColInvoiceAmount {
            get {
                return ResourceManager.GetString("PredicaColInvoiceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string PredicaColInvoicePaid {
            get {
                return ResourceManager.GetString("PredicaColInvoicePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Standard Fee .
        /// </summary>
        internal static string PredicaColNotStandardFee {
            get {
                return ResourceManager.GetString("PredicaColNotStandardFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Order Name.
        /// </summary>
        internal static string PredicaColOrderName {
            get {
                return ResourceManager.GetString("PredicaColOrderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Term Payment Date.
        /// </summary>
        internal static string PredicaColPredicaInvoiceLTPaymentDate {
            get {
                return ResourceManager.GetString("PredicaColPredicaInvoiceLTPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        internal static string PredicaColPredicaInvoicePaymentDate {
            get {
                return ResourceManager.GetString("PredicaColPredicaInvoicePaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Term Payment Date.
        /// </summary>
        internal static string PredicaColPredicaInvoiceSTPaymentDate {
            get {
                return ResourceManager.GetString("PredicaColPredicaInvoiceSTPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predica invoice.
        /// </summary>
        internal static string PredicaCTInvoice {
            get {
                return ResourceManager.GetString("PredicaCTInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base ct for invoice.
        /// </summary>
        internal static string PredicaCTInvoiceDescr {
            get {
                return ResourceManager.GetString("PredicaCTInvoiceDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long term invoice.
        /// </summary>
        internal static string PredicaCTLongTermInvoice {
            get {
                return ResourceManager.GetString("PredicaCTLongTermInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create long term invoice.
        /// </summary>
        internal static string PredicaCTLongTermInvoiceDescr {
            get {
                return ResourceManager.GetString("PredicaCTLongTermInvoiceDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string PredicaCTPredicaOrder {
            get {
                return ResourceManager.GetString("PredicaCTPredicaOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create order.
        /// </summary>
        internal static string PredicaCTPredicaOrderDescr {
            get {
                return ResourceManager.GetString("PredicaCTPredicaOrderDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short term invoice.
        /// </summary>
        internal static string PredicaCTShortTermInvoice {
            get {
                return ResourceManager.GetString("PredicaCTShortTermInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create short term invoice.
        /// </summary>
        internal static string PredicaCTShortTermInvoiceDescr {
            get {
                return ResourceManager.GetString("PredicaCTShortTermInvoiceDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string PredicaListTitleOrders {
            get {
                return ResourceManager.GetString("PredicaListTitleOrders", resourceCulture);
            }
        }
    }
}
